Add Ploomber
kelvins/awesome-mlops pull request #29
Opened 2022-01-14 17:19 UTC by idomic

Added Ploomber to the main section coherent with the value proposition

## What is this tool for?

Ploomber can allow fast development locally, optimizing the runs with incremental builds. It can orchastrate and schedule tasks on tools like airflow, kubeflow, argo and the cloud. It can also run as part of it's own CI and process data as part of the process.

## What's the difference between this tool and similar ones?

Focused on the data scientists, makes the integration easy.

---

Anyone who agrees with this pull request could submit an *Approve* review to it.

2022-01-14 23:39 UTC, kelvins requested changes
Thanks for the contribution @idomic.

Can you please add `Ploomber` to a single section and in alphabetical order?
I would suggest adding it to the "Workflow Tools" section.

2022-01-14 23:59 UTC, idomic commented
@kelvins Done, Where can I add https://github.com/ploomber/soorgeon andhttps://github.com/ploomber/soopervisor ?

2022-01-15 00:43 UTC, kelvins approved these changes

2022-01-15 00:43 UTC, kelvins commented
Good question 🤔 Since they are auxiliary projects related to converting or exporting Ploomber pipelines, I believe they could be included in the "Simplification Tools" section.

I'm merging this PR, but feel free to open other ones.

2022-01-15 00:44 UTC, merged